version: '3'

services:
  livekit:
    image: livekit/livekit-server
    container_name: livekit-server
    ports:
      - "7880:7880"
      - "7881:7881"
      - "7882:7882/udp"
    environment:
      - "LIVEKIT_KEYS=devkey: secretkeythatshouldbeatleast32chars"
      - LIVEKIT_LOG_LEVEL=info
      - LIVEKIT_PORT=7880
      - LIVEKIT_BIND_ADDR=0.0.0.0
      - LIVEKIT_RTC_PORT_RANGE_START=50000
      - LIVEKIT_RTC_PORT_RANGE_END=60000
      - LIVEKIT_RTC_TCP_PORT=7882
      - LIVEKIT_REDIS_HOST=
      - LIVEKIT_TURN_ENABLED=true
      - LIVEKIT_TURN_PORT=3478
      - LIVEKIT_TURN_TLS_PORT=5349
    restart: unless-stopped
    networks:
      - livekit-network

networks:
  livekit-network:
    driver: bridge
